### PR TITLE
task/enable-pgcrypto-for-UUID-creation

### PR DESCRIPTION
**Pull request by ericatripp**
## Problem

When attempting to run migrations that create UUID primary keys in a an app template generated service app, we got the following error:

`PG::UndefinedFunction: ERROR:  function gen_random_uuid() does not exist`

## Solution

Enable pgcrypto when we enable uuid-ossp.

### CODE REVIEW

**Comment by ericatripp** [comment]
> @ericatripp would using `uuid_generate_v4` to generate UUIDs work for you? I believe that is the widely used PG function for migrations that I've seen.

yeah, do you have an example of using it for a primary key without using it for ALL primary keys via a generator?

I'm down with whatever lets us add UUID primary keys easily.

**Comment by ericatripp** [comment]
actually, we don't have permission to use pgcrypto.  I'm going to close and use uuid_generate_v4.  thanks, b.

**Comment by bwebster** [comment]
_(I see this was just closed, but I'll post this comment anyways)_

It looks like as of rails 5.1, the behavior changed slightly and the current suggest approach is to use the newer `gen_random_uuid()` on PostgreSQL >= 9.4.  Here's an excerpt from https://github.com/rails/rails/pull/25395:

> Since version 9.4, the PostgreSQL community recommends moving away from
uuid-ossp's UUID generation functions and using pcrypto's
gen_random_uuid() instead. It generates UUID version 4 by default,
which is what everyone tends to use by the way.

It would be nice if we were able to take advantage of the newer approach in new apps, but I'm not sure how we know the postgresql version for the hosting app.

Some more resources for this:
- https://lab.io/articles/2017/04/13/uuids-rails-5-1/
- [updates to code documentation](https://github.com/rails/rails/pull/27165)

**Comment by brettfishman** [comment]
Ah, thanks for posting this, @bwebster - TIL!

@ericatripp why don't we have permission to use pgcrypto?

**Comment by ericatripp** [comment]
> Ah, thanks for posting this, @bwebster - TIL!
> 
> @ericatripp why don't we have permission to use pgcrypto?

it requires superuser psql permissions to add that extension.  I'm sure that's something we could change.

The issue @bwebster raised about ensuring PostgreSQL >= 9.4 is probably still a blocker for now.

**Comment by bwebster** [comment]
TIL about this
```
fixops pg database-extensions create uuid-ossp -a APP -e production
```

It's somewhat related to the conversation above and thought it was worth mentioning.  See [this technical topic](https://github.com/stitchfix/eng-wiki/blob/master/technical-topics/new-app/deploy.md#deploy-to-production) for more.

**Pull request closed without merging**
