### PR TITLE
Add simple options for disabling API authorization in development

### PR DESCRIPTION
**Pull request by eingenito**
What do people think about this? I think the overhead of maintaining API keys in dev in the local databases is worth eliminating. There are lots of ways to do this, but this one seem easy.

### CODE REVIEW

**Comment by davetron5000** [comment]
Env-specific things that remove security checks make me nervous.

I wonder if this would be better solved by having the `bin/setup` in an app that consumes a service generate the key in the needed services?  The `generate_api_key` rake task could be more shell-compliant, and this could be run to create the consuming app's `.env`

But, if you wanted to disable this in dev (which I'm still not sure we should do), I think a better way would be to not configure the middleware.

**Comment by eingenito** [comment]
@davetron5000 I really want to be able to disable this in development - my feeling is it is pure overhead and delivers minimal assurance regarding the successful use of keys in production. The stitches gem could already be configured differently per environment if we wanted to - it's just verbose; we have to configure thusly: https://github.com/stitchfix/stitches#avoiding-auto-magical-set-up and opt out of the ApiKey middleware for some Rails.envs, but that works.

Are you okay with me starting to make that change in each of the services that we're consuming in Kufak? Or would you prefer me to leave keys enabled as they are? As for bin/setup; the need to know file paths to consumed services, and switching rubies/gemsets to invoke their local rake tasks with rvm or rbenv/chruby support seems complicated so I think personally I'd rather just deal with the keys myself than maintain that.

**Comment by davetron5000** [comment]
Yeah, good point on the RVM/bundle stuff.  Probably not as easy as I'm making it out to be (though  you could still do it at the DB level I guess).

One thing to consider is that many of our services require an ApiClient to attach to any created records, so any feature like this won't eliminate the need to have *some* ApiClient in those services.

I wonder if the best way would be for you to set it up manually how you want it in the services where you can avoid creating keys and then see if that leads to something that can be rolled into this?  Something that makes it *really* hard to disable in staging/production/test would be ideal if we have to have it (but my experience is that any env-specific logic is trouble brewing).

**Comment by joecannatti** [comment]
I think my attempt at a setup script for Kufaq might be worth looking at here. It doesn't really resolve any of the questions being raised above, but is an example of just trying to automate setting it up correctly.

https://github.com/stitchfix/kufak-suite

**Comment by davetron5000** [comment]
super old, so closing.  re-open if we want further discussion

**Pull request closed without merging**
